name: Docs check
on:
  pull_request:
    paths:
      - '.github/workflows/docs-check.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Docs dependencies
        run: python3 -m pip install -r docs/requirements.txt

      - name: Build and push Docs
        run: |
          make html SPHINXOPTS="-W"
