name: Tests

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/tests.yml'
      - 'lib/**'

permissions:
  contents: read

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests-success:
    permissions:
      contents: none
    runs-on: ubuntu-22.04
    needs: [nc-py-api-pgsql]
    name: Tests-OK
    steps:
      - run: echo "No Tests required"
